### PR TITLE
feat: Integrate LAN API Interface

### PR DESCRIPTION
**Pull request by alboiuvlad29**
Hey! 👋

I have created this PR that integrates the new LAN API Interface introduced by Govee in v5.2.0.

I am not a JavaScript developer, so there's definitely some refactoring remaining to be done but I think this progressed nicely. I will be marking this as DRAFT, as there is still some more work to be done but still creating the PR to get some feedback in the meantime.

### Use Case:
To improve communication speed, reliability and to to mitigate intermediary communications, we should be able to communicate with supported Govee devices on the local network. 

### Description
Govee has introduced a new LAN API Interface for some device models (firmware update required) with more to be updated. The documentation can be found here: https://app-h5.govee.com/user-manual/wlan-guide

Then when sending update commands, the code will check `lanModels` to see wether we should attempt sending commands over LAN for this device. If  commands can be sent over LAN and a supported command is attempted, the command will be sent and other methods will be ignored. Otherwise, the previous behaviour shouldn't be affected.

### Acceptance Criteria:
- Discover the devices on local network
- Be able to query a device's state on local network
- Be able to send supported commands through LAN
- Unsupported commands should fallback to any other previous method of communication (if available)

### Testing Steps:
1. Go to Govee app -> Select Supported Device -> Settings (gear Icon) -> Enable LAN Control
2. Check that the device appears in Homebridge logs and all supported commands work

### Tasks Remaining
 - [x] LAN devices discovery
 - [x] Standard commands (turn on/off, color change) implemented
 - [x] Receive device status and update internal state after a command was sent
 - [x] Prefer polling for device state on LAN compatible devices rather than API/HTTP
 - [x] Have logs respect debug settings
 - [x] Send update commands faster on LAN devices (i.e., controlInterval should be much lower in this case)
 - [x] Device discovery without relying on API? (I.e, be able to work fully offline without API/HTTP/AWS)

### CODE REVIEW

**Comment by bwp91** [comment]
oh wow! 
i’ll have a good look at this later but where are the official docs for the lan API?

**Comment by alboiuvlad29** [comment]
@bwp91 In the app! 🙂 A bit strange, I would've hoped they'd host it somewhere.
Go to Govee app -> Select Supported Device -> Settings (gear Icon) -> API Icon next to`LAN Control` option.

**Comment by bwp91** [comment]
I see, I guess it’s handy to have it in the app there for users, but, hosted docs would also be useful! I don’t own any of the devices that support this, so guess i’m relying on you a bit (well quite a lot!) here.

Really appreciate your effort in implementing this, i hope it will be helpful for a lot of users who are tired of the wifi issues, plus it’s a great addition to the plugin.

None of my other homebridge plugins have so many different connection methods so this plugin, whilst already complicated, is going to be a bit crazy with this new method!

**Comment by bwp91** [comment]
Would you be happy for me to publish this to a beta version?

**Comment by alboiuvlad29** [comment]
Hey @bwp91, I think it would be a bit too early? What do you think? To me while it worked properly, I think there could be some improvements made. I'm just hoping that I didn't introduce some bugs, but I'm hoping to work more on this when I come back from abroad (I'm not home until early September and can't test it anymore).

But if you think it would make sense, maybe an alpha version would be better to get some feedback?

**Comment by alboiuvlad29** [comment]
@bwp91 I've made a couple of changes while abroad and since I'm back, I was able to test them. I've opened the PR as Ready for Review and everything works in LAN only mode. There seem to be some incompatibility issues with the other modes (i.e., API) and not sure how to go around them.

Updating color very fast throws this error when API key is also provided.
image

And if the devices are added with LAN(since they don't have names) they should be updated by API
image

Thoghts?

**Comment by bwp91** [comment]
Thank you so much for your work on this.
I have merged in already and released as part of a v6 beta.
I need to rework the logic of how the different connection methods work together. Or whether to completely separate them.
I am also happy to look into these errors you are reporting. I don't have a device that supports LAN mode so will be in contact if I push a potential fix and need it tested!

**Comment by alboiuvlad29** [comment]
Awesome, thanks for the beta release!

Sure thing, feel free to reach out and I'll be happy to test! 🙂

**Pull request merged**
